import React from 'react';
import { useSelector } from 'react-redux';
import { IconChartBar, IconCheck, IconClock, IconAlertTriangle, IconBolt, IconTrendingUp } from '@tabler/icons-react';
import { TaskDeskItem } from '../automation/types';

export default function TaskAnalyticsView() {
  const tasks = useSelector((s: any) => s.taskDesk.tasks);
  const rules = useSelector((s: any) => s.taskDesk.rules);

  const totalTasks = tasks.length;
  const pendingTasks = tasks.filter((t: TaskDeskItem) => t.status === 'pending').length;
  const inProgressTasks = tasks.filter((t: TaskDeskItem) => t.status === 'in_progress').length;
  const completedTasks = tasks.filter((t: TaskDeskItem) => t.status === 'completed').length;
  const criticalTasks = tasks.filter((t: TaskDeskItem) => t.priority === 'critical').length;

  const completionRate = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  // Breakdown by trigger type
  const triggerCounts: Record<string, number> = {};
  tasks.forEach((t: TaskDeskItem) => {
    const label = t.triggerLabel || t.triggerType || 'Manual';
    triggerCounts[label] = (triggerCounts[label] || 0) + 1;
  });

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Metric Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '16px' }}>
        <div
          style={{
            background: 'rgba(30, 41, 59, 0.6)',
            border: '1px solid rgba(255, 255, 255, 0.08)',
            borderRadius: '12px',
            padding: '18px',
          }}
        >
          <div style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: 600 }}>TOTAL AUTOMATED TASKS</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 800, color: '#f8fafc', margin: '4px 0' }}>{totalTasks}</div>
          <div style={{ fontSize: '0.75rem', color: '#38bdf8', display: 'flex', alignItems: 'center', gap: '4px' }}>
            <IconTrendingUp size={14} /> Generated by Automation Engine
          </div>
        </div>

        <div
          style={{
            background: 'rgba(30, 41, 59, 0.6)',
            border: '1px solid rgba(255, 255, 255, 0.08)',
            borderRadius: '12px',
            padding: '18px',
          }}
        >
          <div style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: 600 }}>RESOLUTION RATE</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 800, color: '#4ade80', margin: '4px 0' }}>{completionRate}%</div>
          <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
            {completedTasks} completed out of {totalTasks} total
          </div>
        </div>

        <div
          style={{
            background: 'rgba(30, 41, 59, 0.6)',
            border: '1px solid rgba(255, 255, 255, 0.08)',
            borderRadius: '12px',
            padding: '18px',
          }}
        >
          <div style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: 600 }}>PENDING / IN PROGRESS</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 800, color: '#facc15', margin: '4px 0' }}>
            {pendingTasks + inProgressTasks}
          </div>
          <div style={{ fontSize: '0.75rem', color: '#cbd5e1' }}>
            {pendingTasks} Pending, {inProgressTasks} In Progress
          </div>
        </div>

        <div
          style={{
            background: 'rgba(30, 41, 59, 0.6)',
            border: '1px solid rgba(255, 255, 255, 0.08)',
            borderRadius: '12px',
            padding: '18px',
          }}
        >
          <div style={{ fontSize: '0.8rem', color: '#94a3b8', fontWeight: 600 }}>CRITICAL ALERTS</div>
          <div style={{ fontSize: '1.8rem', fontWeight: 800, color: '#f87171', margin: '4px 0' }}>{criticalTasks}</div>
          <div style={{ fontSize: '0.75rem', color: '#f87171' }}>High priority emergency tasks</div>
        </div>
      </div>

      {/* Trigger Distribution Breakdown */}
      <div
        style={{
          background: 'rgba(30, 41, 59, 0.6)',
          border: '1px solid rgba(255, 255, 255, 0.08)',
          borderRadius: '12px',
          padding: '20px',
        }}
      >
        <h3 style={{ margin: '0 0 16px 0', fontSize: '1.05rem', fontWeight: 700, color: '#f8fafc' }}>
          Tasks Generated by Trigger Category
        </h3>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {Object.entries(triggerCounts).map(([label, count]) => {
            const pct = totalTasks > 0 ? Math.round((count / totalTasks) * 100) : 0;
            return (
              <div key={label}>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '4px' }}>
                  <span style={{ color: '#e2e8f0', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '6px' }}>
                    <IconBolt size={14} color="#38bdf8" /> {label}
                  </span>
                  <span style={{ color: '#cbd5e1', fontWeight: 600 }}>
                    {count} tasks ({pct}%)
                  </span>
                </div>
                <div
                  style={{
                    height: '8px',
                    width: '100%',
                    background: 'rgba(15, 23, 42, 0.6)',
                    borderRadius: '4px',
                    overflow: 'hidden',
                  }}
                >
                  <div
                    style={{
                      height: '100%',
                      width: `${pct}%`,
                      background: 'linear-gradient(90deg, #3b82f6, #0284c7)',
                      borderRadius: '4px',
                      transition: 'width 0.5s ease',
                    }}
                  />
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
